server {
  listen 8001;
  host 127.0.0.1;
  server_name test;
  error_page 404 Page/error/400/404.html;
  client_max_body_size 1024;
  root Page/;
  index index.html;

  location /tours {
      root Page/;
      autoindex on;
      allow_methods POST GET;
      index index.html;
      return ./Page/return/index.html;
      alias  Page/;
  }

  location /cgi {
      root ./;
      cgi_path /usr/bin/python3 /bin/bash;
      cgi_ext .py .sh;
  }
}
