server {
    listen 0.0.0.0:8000;
    listen 8001;
    listen 8002;
    root test_us/roots;
    server_name weebserv;
    autoindex off;
    index index.html;
    client_max_body_size 10;

    location *.test {
        cgi_path test_us/cgi_tester
    }
}

server {
	listen 0.0.0.0:8000;
	listen 8001;
	listen 8002;

	root test_us/root/el_secundo;
	server_name el_secundo;

	allow_methods GET;

	autoindex off;
	index index.html;

	client_max_body_size 10;

	location *.test {
		cgi_path test_us/cgi_tester;
	}
}
